# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskid', models.CharField(max_length=20)),
                ('target', models.TextField()),
                ('ip', models.TextField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Plugins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskid', models.CharField(max_length=20)),
                ('target', models.TextField()),
                ('ip', models.TextField()),
                ('port', models.CharField(max_length=10)),
                ('plugid', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('data', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskid', models.CharField(max_length=20)),
                ('target', models.TextField()),
                ('domain', models.CharField(max_length=5)),
                ('service', models.CharField(max_length=5)),
                ('weakfile', models.CharField(max_length=5)),
                ('status', models.CharField(max_length=5)),
                ('starttime', models.DateField(auto_now=True)),
                ('endtime', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Weakfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskid', models.CharField(max_length=20)),
                ('target', models.TextField()),
                ('plugid', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('data', models.CharField(max_length=100)),
            ],
        ),
    ]
