# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 06:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gscan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='taskname',
            field=models.CharField(default=datetime.datetime(2016, 3, 6, 6, 49, 30, 643177, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
