# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gscan', '0002_tasks_taskname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='endtime',
            field=models.DateField(null=True),
        ),
    ]
