# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gscan', '0004_auto_20160306_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='taskid',
            field=models.CharField(max_length=50),
        ),
    ]
