# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-02 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gscan', '0005_auto_20160317_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasTmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskid', models.CharField(max_length=20)),
                ('ip', models.TextField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
