# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gscan', '0006_mastmp'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugins',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
