# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gscan', '0007_plugins_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.TextField()),
                ('http', models.BooleanField()),
                ('description', models.TextField()),
            ],
        ),
    ]
