# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-28 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gscan', '0009_weakfile_weakfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plugins',
            old_name='name',
            new_name='mark',
        ),
        migrations.RemoveField(
            model_name='service',
            name='plugid',
        ),
        migrations.AddField(
            model_name='service',
            name='pluginpath',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
