# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gscan', '0012_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
