# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gscan', '0013_delete_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plugins',
            old_name='mark',
            new_name='name',
        ),
        migrations.AddField(
            model_name='plugins',
            name='port',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plugins',
            name='type',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
