# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gscan', '0014_auto_20160517_2121'),
    ]

    operations = [
       
        
    ]
