# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gscan', '0016_auto_20160517_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.TextField()),
                ('http', models.BooleanField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='ScanConfig',
        ),
    ]
