# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gscan', '0017_auto_20160517_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('ports', models.TextField()),
                ('description', models.TextField()),
                ('createtime', models.DateField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PortConfig',
        ),
    ]
