# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gscan', '0019_tasks_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('ip', models.TextField()),
                ('logintime', models.TextField()),
            ],
        ),
    ]
